micronaut:
  application:
    name: demo
datasources:
  default:
    url: jdbc:mariadb://localhost:3306/coba
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: ''
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
